AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ArtifactName:
    Type: String
    Description: The artifact to deploy
    MinLength: '0'
Resources:
  MimePreprocessLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: "mp-codepipeline"
        S3Key: "lambda-functions/{{ArtifactName}}"
      FunctionName:
        Fn::Sub: "dev-minh-lambda-test"
      Handler: minh.gradle.lambda.LambdaRequestHandler::handleRequest
      MemorySize: 1024
      Role: arn:aws:iam::195702235524:role/service-role/lambda-canary
      Runtime: java8
      Timeout: 90