AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LambdaS3Bucket:
    Type: String
    Description: 'The S3 bucket to retrieve Lambda function package'
  LambdaS3Directory:
    Type: String
    Description: 'The S3 bucket directory that keeps all lambda functions'
    MinLength: '0'
  Lambda1ArtifactName:
    Type: String
    Description: 'The artifact to deploy'
    MinLength: '0'
  Lambda1Role:
    Type: String
    Description: 'The role to be used with lambda function'
    MinLength: '0'
  Lambda1MemorySize:
    Type: Number
    Description: 'Memory size between 128 MB - 1536 MB and multiple of 64'
    MinValue: '128'
    MaxValue: '1536'
    Default: '128'
  Lambda1Timeout:
    Type: Number
    Description: 'lambda processing timeout'
  Timestamp:
    Type: Number
    Description: 'Timestamp of stack update'
Resources:
  MimePreprocessLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code: { S3Bucket: { Ref: LambdaS3Bucket }, S3Key: { 'Fn::Join': ["/",[{ Ref: LambdaS3Directory }, { { 'Fn::Join': ["-",[{ Ref: Ref: Lambda1ArtifactName }, { Ref: Timestamp }]] } }]] } }
      FunctionName: { 'Fn::Sub': dev-minh-lambda-test }
      Handler: 'com.dice.aws.lambda.LambdaRequestHandler::handleRequest'
      MemorySize: { Ref: Lambda1MemorySize }
      Role: { Ref: Lambda1Role }
      Runtime: java8
      Timeout: { Ref: Lambda1Timeout }
